import Breadcrumb from "../_components/breadcrumb";
import TopNav from "../_components/top-nav";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <TopNav />
      <div className="container mx-auto pt-10">
        <Breadcrumb />
        {children}
      </div>
    </>
  );
}
