import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import TopNav from "~/components/top-nav";
import { TRPCReactProvider } from "~/trpc/react";
import Breadcrumb from "../_components/breadcrumb";


export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <TopNav />
          <div className="container mx-auto pt-10">
            <Breadcrumb />
            {children}
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
