import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import AdminSideNav from "../_components/admin-side-nav";
import AdminTopNav from "../_components/admin-top-nav";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex flex-row min-h-dvh">
        <AdminSideNav />
        <div className="flex flex-col w-full">
          <AdminTopNav />

          <TRPCReactProvider>
            <main className="container pt-10 w-full bg-second">
              {children}
            </main>
          </TRPCReactProvider>
        </div>
      </body>
    </html>
  );
}
